### ISSUE TITLE
Multiple Installation issues...

### ISSUE THREAD

**Issue by bewearhugs** [kylepaulsen/discord-plays-games#1]
Issue1)
npm ERR! JSON.parse Unexpected token } in JSON at position 234 while parsing near '...ied\" && exit 1",
*removing the comma after -exit 1" in package JSON- appears to fix this

Issue2)
Using Node v12.18.2 ----- the npm install freaks out with this:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.

found this https://github.com/octalmage/robotjs/issues/398 trying now for fix
^^^no luck so far :(

attempted installing robotjs 0.4.7 separately using 'npm i robotjs@0.4.7'   - returns same errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.

Found this link
https://www.npmjs.com/package/prebuild-install
attempting to use:
npm i prebuild-install

results in:

npm WARN discord-plays-games@1.0.0 No repository field.

Uninstalled node.js, downloading old version that was applicable when this was posted...
Hope this works... https://nodejs.org/en/blog/release/v9.11.1/

running npm install after downgrading node.js results in:

gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:379:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:178:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\camer\Desktop\discord-plays-games-master\node_modules\robotjs
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN discord-plays-games@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.

removing node.js v-9.11.1
reinstalling latest version,
starting from fresh copy of repo again.... sigh....

ok so i followed steps after removing comma, npm install still gave multiple errors but i ignored and ran start node.js, it made config, i added token, ran start node.js again and got this error loop:

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'robotjs'
Require stack:
- C:\Users\camer\Desktop\discord-plays-games-master\keyboardRobot.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:841:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1025:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:72:18)[39m
    at Object.<anonymous> (C:\Users\camer\Desktop\discord-plays-games-master\keyboardRobot.js:4:15)
[90m    at Module._compile (internal/modules/cjs/loader.js:1137:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:985:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\camer\\Desktop\\discord-plays-games-master\\keyboardRobot.js'[39m
  ]
}
=== KEYBOARDROBOT FORK EXITED! Restarting...
(8/5/2020 11:46:5) DISCORD BOT: running...

which loops infinitely until I ctrl+C to close

Im focused on this line specifically:

Error: Cannot find module 'robotjs'

so I checked node_modules and sure enough its not there, i see robotjs has 2 dpendencies so i ran 

-npm i prebuild-install

and

-npm i nan

then attempted to install robotjs via   ---      npm i robotjs@0.4.7

STILL RESULTS IN!!!!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the robotjs@0.4.7 install script.

**Comment by bewearhugs** [comment]
i give up lol
